spring.datasource.url=jdbc:postgresql://localhost:5432/kontroltoo
spring.datasource.username=postgres
spring.datasource.password=3echekAs
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
